### ISSUE TITLE
Vagrant role - rpm install fails

### ISSUE THREAD

**Issue by bparry02** [crivetimihai/ansible_virtualization#10]
When I try to install vagrant 2.2.7 on RHEL 8.3 with ansible 2.9.16, the package install task fails with:
```
TASK [crivetimihai.virtualization.vagrant : install RedHat packages] *********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for vagrant-1:2.2.7-1.x86_64"}
```

I believe this occurs because the RPM is not signed. Instead Hashicorp suggests [validating the checksum](https://www.hashicorp.com/security). However, I did not experience this issue when installing on RHEL 8.0 with a slightly older version of ansible. I suppose it's possible a python module version changed, such as the one for dnf.

To work around this issue, I disabled the gpg check in my fork:
```
- name: install RedHat packages
  package:
    name: "{{ redhat_packages }}"
    state: present
    disable_gpg_check: yes
  become: yes
```
