### ISSUE TITLE
Vagrant role - mismatched variable name for RHEL

### ISSUE THREAD

**Issue by bparry02** [crivetimihai/ansible_virtualization#7]
In the Vagrant role, the task for RedHat references a variable `redhat_packages`, however the variable defined in the vars file is `rhel_packages`.

The variable name should be changed to be consistent in the task and the vars file.

The workaround for this issue is to set the expected variable to the one defined in the vars file:
```
- hosts: all
  tasks:
    - import_role:
        name: crivetimihai.virtualization.vagrant
      vars:
        redhat_packages: "{{ rhel_packages }}"
```
